invalid: refatorada a função acel #48
eguatech/egua pull request #101
Opened 2021-02-06 23:11 UTC by barbozafernando

Foi refatorado a verificação de parâmetros e trocado o nome da função #48

2021-02-06 23:14 UTC, barbozafernando commented
Tomei a liberdade de alterar o nome da função pra `aceleracao` pois fica mais nítido pra que ela serve.

2021-02-07 16:53 UTC, leonelsanchesdasilva requested changes

2021-02-07 16:53 UTC, leonelsanchesdasilva commented on web/dist.js
> -=======
Isso me parece um conflito de merge.

2021-02-07 17:43 UTC, barbozafernando commented on web/dist.js
> -=======
Rapaz, e olhando aqui, não tem esse trecho aí não.

2021-02-07 17:47 UTC, barbozafernando commented on web/dist.js
> -=======
Tentei editar o arquivo pelo próprio Github, mas lá também não aparece esse trecho.

2021-02-10 00:10 UTC, lucaspompeun commented
> Tomei a liberdade de alterar o nome da função pra `aceleracao` pois fica mais nítido pra que ela serve. Se não tiver problema, posso abrir outro PR corrigindo a função lá na documentação do Egua.

@barbozafernando de fato fica melhor mesmo. Ótima ideia. Acho que a biblioteca eguamat não está na documentação ainda, preferi corrigir todos os bugs da mesma antes de documentar.

2021-02-10 00:11 UTC, lucaspompeun commented on web/dist.js
> -=======
Esse arquivo é gerado automaticamente no build pra web.

2021-02-10 00:12 UTC, lucaspompeun approved these changes
Me parece tudo correto, qualquer erro que tenha passado o github actions irá apontar

2021-02-10 00:13 UTC, merged