Hackertober Fest: repaginação visual
eguatech/egua pull request #152
Opened 2022-10-15 00:28 UTC by ErickLemos

Antes de tudo gostaria de dizer que vou trabalhar no projeto no decorrer do mês com incetivo do hackertober fest, poderia adicionar as tags ao projeto ou ao pull request? Desde já agradeço!

Continuando, fiz uma repaginação na aplicação com base em design mais modernos.

Antes: 
![Captura de tela de 2022-10-14 21-26-14](https://user-images.githubusercontent.com/26334984/195960664-3cafa04f-6c1d-4946-a4e0-103e444c5875.png)

Depois:
![Captura de tela de 2022-10-14 21-25-53](https://user-images.githubusercontent.com/26334984/195960674-cea12313-8d26-4e97-87f2-89a2dd97b90a.png)

2022-10-15 20:11 UTC, lucaspompeun requested changes
Basta corrigir o bug e testar a cor. Adorei seu PR e será certamente aceito

2022-10-15 20:11 UTC, lucaspompeun commented on web/style.css
> +html, body, * {
Remover ", body, *" devido ao seguinte bug visual:
![image](https://user-images.githubusercontent.com/8001253/196005794-48c6ed76-fe42-4cf5-9a01-272c3e32b998.png)

2022-10-15 20:11 UTC, lucaspompeun commented on web/style.css
> +  background-color: #7d11d1;
Adorei a remoção do gradiente, aqui sugiro um teste com a cor "#ea515e", o que lhe agradar mais manteremos.

2022-10-15 20:12 UTC, lucaspompeun commented
@ErickLemos o PR #151 ainda deve ser revisado e aceito? Percebi que este PR sobrepõe aquele.

2022-10-15 20:16 UTC, lucaspompeun commented
@ErickLemos , favor verifique se as labels do repo estão corretas para o hacktoberfest

![image](https://user-images.githubusercontent.com/8001253/196005962-deb6b251-5516-4a52-98f5-7b951d895eeb.png)

Existe algum outro requisito que o repo deve cumprir? Caso positivo favor sinalizar para que eu possa adequar.
Desde já agradeço sua contribuição com a linguagem

2022-10-15 23:10 UTC, ErickLemos commented
O site da hackertober fest identificou com sucesso o PR

2022-10-15 23:14 UTC, ErickLemos commented
correção do problema de seleção e ajuste nas cores:
![Captura de tela de 2022-10-15 20-09-02](https://user-images.githubusercontent.com/26334984/196010881-fe7e01fe-1555-4812-8f14-0cb68c796adb.png)
![Captura de tela de 2022-10-15 20-09-49](https://user-images.githubusercontent.com/26334984/196010883-b6eee638-9c49-406b-877f-781e27074a5f.png)

2022-10-16 02:09 UTC, lucaspompeun approved these changes

2022-10-16 02:09 UTC, merged