Testes em biblioteca eguamat
eguatech/egua pull request #8
Opened 2020-10-28 00:18 UTC by othonalberto

2021-02-07 16:54 UTC, leonelsanchesdasilva requested changes
Creio que há conflitos de merge.

2021-02-07 16:54 UTC, leonelsanchesdasilva commented on src/lib/__tests__/eguamat.test.js
> +    it('throws when num is null', () => {
Creio que comentários de testes devam ser em português, não?

2021-02-10 00:24 UTC, lucaspompeun commented
@othonalberto vamos fazer o merge e implementar na automação. É possível alterar apenas o arquivo `package.json`? Ou até mesmo excluir deste PR? Fica fácil adicionar posteriormente as alterações que seriam feitas nele.

2021-02-20 02:08 UTC, leonelsanchesdasilva commented
@lucaspompeun O que está faltando nessa PR, além do conflito de merge?

2021-02-23 22:20 UTC, lucaspompeun commented
> @lucaspompeun O que está faltando nessa PR, além do conflito de merge?

Exatamente isso, apenas o conflito de merge.

2021-02-24 02:35 UTC, othonalberto commented
@leonelsanchesdasilva @lucaspompeun Boa noite! Peço perdão pela demora.

@lucaspompeun, devo manter o package.json como está na branch principal?

2021-02-24 15:05 UTC, lucaspompeun commented
> @leonelsanchesdasilva @lucaspompeun Boa noite! Peço perdão pela demora.
> 
> @lucaspompeun, devo manter o package.json como está na branch principal?

Isso mesmo. acredito que seja só igualar ele

2021-11-29 04:10 UTC, leonelsanchesdasilva approved these changes

2021-11-29 04:14 UTC, merged